/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryPageRouteImport } from './routes/history-page'
import { Route as ChartPageRouteImport } from './routes/chart-page'
import { Route as CalendarPageRouteImport } from './routes/calendar-page'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const HistoryPageRoute = HistoryPageRouteImport.update({
  id: '/history-page',
  path: '/history-page',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartPageRoute = ChartPageRouteImport.update({
  id: '/chart-page',
  path: '/chart-page',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarPageRoute = CalendarPageRouteImport.update({
  id: '/calendar-page',
  path: '/calendar-page',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar-page': typeof CalendarPageRoute
  '/chart-page': typeof ChartPageRoute
  '/history-page': typeof HistoryPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar-page': typeof CalendarPageRoute
  '/chart-page': typeof ChartPageRoute
  '/history-page': typeof HistoryPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar-page': typeof CalendarPageRoute
  '/chart-page': typeof ChartPageRoute
  '/history-page': typeof HistoryPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/calendar-page' | '/chart-page' | '/history-page'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/calendar-page' | '/chart-page' | '/history-page'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calendar-page'
    | '/chart-page'
    | '/history-page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CalendarPageRoute: typeof CalendarPageRoute
  ChartPageRoute: typeof ChartPageRoute
  HistoryPageRoute: typeof HistoryPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history-page': {
      id: '/history-page'
      path: '/history-page'
      fullPath: '/history-page'
      preLoaderRoute: typeof HistoryPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart-page': {
      id: '/chart-page'
      path: '/chart-page'
      fullPath: '/chart-page'
      preLoaderRoute: typeof ChartPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar-page': {
      id: '/calendar-page'
      path: '/calendar-page'
      fullPath: '/calendar-page'
      preLoaderRoute: typeof CalendarPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CalendarPageRoute: CalendarPageRoute,
  ChartPageRoute: ChartPageRoute,
  HistoryPageRoute: HistoryPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
