/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as TabBarRouteImport } from './routes/TabBar'
import { Route as HistoryPageRouteImport } from './routes/HistoryPage'
import { Route as DashBoardRouteImport } from './routes/DashBoard'
import { Route as CalendarPageRouteImport } from './routes/CalendarPage'
import { Route as IndexRouteImport } from './routes/index'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TabBarRoute = TabBarRouteImport.update({
  id: '/TabBar',
  path: '/TabBar',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryPageRoute = HistoryPageRouteImport.update({
  id: '/HistoryPage',
  path: '/HistoryPage',
  getParentRoute: () => rootRouteImport,
} as any)
const DashBoardRoute = DashBoardRouteImport.update({
  id: '/DashBoard',
  path: '/DashBoard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarPageRoute = CalendarPageRouteImport.update({
  id: '/CalendarPage',
  path: '/CalendarPage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/CalendarPage': typeof CalendarPageRoute
  '/DashBoard': typeof DashBoardRoute
  '/HistoryPage': typeof HistoryPageRoute
  '/TabBar': typeof TabBarRoute
  '/auth': typeof AuthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/CalendarPage': typeof CalendarPageRoute
  '/DashBoard': typeof DashBoardRoute
  '/HistoryPage': typeof HistoryPageRoute
  '/TabBar': typeof TabBarRoute
  '/auth': typeof AuthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/CalendarPage': typeof CalendarPageRoute
  '/DashBoard': typeof DashBoardRoute
  '/HistoryPage': typeof HistoryPageRoute
  '/TabBar': typeof TabBarRoute
  '/auth': typeof AuthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/CalendarPage'
    | '/DashBoard'
    | '/HistoryPage'
    | '/TabBar'
    | '/auth'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/CalendarPage'
    | '/DashBoard'
    | '/HistoryPage'
    | '/TabBar'
    | '/auth'
  id:
    | '__root__'
    | '/'
    | '/CalendarPage'
    | '/DashBoard'
    | '/HistoryPage'
    | '/TabBar'
    | '/auth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarPageRoute: typeof CalendarPageRoute
  DashBoardRoute: typeof DashBoardRoute
  HistoryPageRoute: typeof HistoryPageRoute
  TabBarRoute: typeof TabBarRoute
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/TabBar': {
      id: '/TabBar'
      path: '/TabBar'
      fullPath: '/TabBar'
      preLoaderRoute: typeof TabBarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/HistoryPage': {
      id: '/HistoryPage'
      path: '/HistoryPage'
      fullPath: '/HistoryPage'
      preLoaderRoute: typeof HistoryPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/DashBoard': {
      id: '/DashBoard'
      path: '/DashBoard'
      fullPath: '/DashBoard'
      preLoaderRoute: typeof DashBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CalendarPage': {
      id: '/CalendarPage'
      path: '/CalendarPage'
      fullPath: '/CalendarPage'
      preLoaderRoute: typeof CalendarPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarPageRoute: CalendarPageRoute,
  DashBoardRoute: DashBoardRoute,
  HistoryPageRoute: HistoryPageRoute,
  TabBarRoute: TabBarRoute,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
